### ISSUE TITLE
Uncaught TypeError: nodemon.setArgs(...).then is not a function

### ISSUE THREAD

**Issue by pciazynski** [pdxjohnny/nodemon-atom#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Ubuntu 14.04.3
**Thrown From**: [nodemon-atom](https://github.com/pdxjohnny/nodemon-atom) package, v0.1.0
### Stack Trace

Uncaught TypeError: nodemon.setArgs(...).then is not a function

```
At /home/piotr/.atom/packages/nodemon-atom/lib/nodemon-atom.coffee:49

TypeError: nodemon.setArgs(...).then is not a function
  at atom-workspace.<anonymous> (/home/piotr/.atom/packages/nodemon-atom/lib/nodemon-atom.coffee:49:82)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/atom/resources/app.asar/src/command-registry.js:143:19)
  at EventEmitter.module.exports.WindowEventHandler.handleIPCCommand (/opt/atom/resources/app.asar/src/window-event-handler.js:213:28)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```
### Commands

```
     -7:37.7.0 nodemon-atom:run (atom-text-editor.editor.is-focused)
     -6:10.1.0 settings-view:open (atom-text-editor.editor.is-focused)
     -5:25.3.0 nodemon-atom:menu (atom-text-editor.editor.is-focused)
     -5:24.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -5:23.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:11.6.0 nodemon-atom:menu (atom-text-editor.editor.is-focused)
     -0:10.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:10.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 nodemon-atom:run (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "nodemon-atom": {}
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.13
file-icons, v1.6.11
highlight-selected, v0.10.1
linter, v1.10.0
linter-csslint, v1.1.0
linter-htmlhint, v0.2.1
linter-jshint, v1.2.1
minimap, v4.16.0
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
node-debugger, v1.1.9
nodemon-atom, v0.1.0
pigments, v0.18.1
selection-highlight, v0.1.4
tag, v0.3.0

# Dev
No dev packages
```

**Comment by niklasfink** [comment]
+1
Plugin not working.

**Comment by pulipulichen** [comment]
+1

I got exception always:

````
Uncaught TypeError: nodemon.setArgs(...).then is not a function
````
